// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CloserMock is an autogenerated mock type for the Closer type
type CloserMock struct {
	mock.Mock
}

type CloserMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CloserMock) EXPECT() *CloserMock_Expecter {
	return &CloserMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *CloserMock) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CloserMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type CloserMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CloserMock_Expecter) Close(ctx interface{}) *CloserMock_Close_Call {
	return &CloserMock_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *CloserMock_Close_Call) Run(run func(ctx context.Context)) *CloserMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CloserMock_Close_Call) Return(_a0 error) *CloserMock_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CloserMock_Close_Call) RunAndReturn(run func(context.Context) error) *CloserMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewCloserMock creates a new instance of CloserMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloserMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloserMock {
	mock := &CloserMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
