// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InterfaceAMock is an autogenerated mock type for the InterfaceA type
type InterfaceAMock struct {
	mock.Mock
}

type InterfaceAMock_Expecter struct {
	mock *mock.Mock
}

func (_m *InterfaceAMock) EXPECT() *InterfaceAMock_Expecter {
	return &InterfaceAMock_Expecter{mock: &_m.Mock}
}

// A provides a mock function with given fields:
func (_m *InterfaceAMock) A() {
	_m.Called()
}

// InterfaceAMock_A_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'A'
type InterfaceAMock_A_Call struct {
	*mock.Call
}

// A is a helper method to define mock.On call
func (_e *InterfaceAMock_Expecter) A() *InterfaceAMock_A_Call {
	return &InterfaceAMock_A_Call{Call: _e.mock.On("A")}
}

func (_c *InterfaceAMock_A_Call) Run(run func()) *InterfaceAMock_A_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InterfaceAMock_A_Call) Return() *InterfaceAMock_A_Call {
	_c.Call.Return()
	return _c
}

func (_c *InterfaceAMock_A_Call) RunAndReturn(run func()) *InterfaceAMock_A_Call {
	_c.Call.Return(run)
	return _c
}

// NewInterfaceAMock creates a new instance of InterfaceAMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterfaceAMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *InterfaceAMock {
	mock := &InterfaceAMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
