// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// InterfaceAMock is an autogenerated mock type for the InterfaceA type
type InterfaceAMock struct {
	mock.Mock
}

type InterfaceAMock_Expecter struct {
	mock *mock.Mock
}

func (_m *InterfaceAMock) EXPECT() *InterfaceAMock_Expecter {
	return &InterfaceAMock_Expecter{mock: &_m.Mock}
}

// A provides a mock function with given fields:
func (_m *InterfaceAMock) A() {
	_m.Called()
}

// InterfaceAMock_A_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'A'
type InterfaceAMock_A_Call struct {
	*mock.Call
}

// A is a helper method to define mock.On call
func (_e *InterfaceAMock_Expecter) A() *InterfaceAMock_A_Call {
	return &InterfaceAMock_A_Call{Call: _e.mock.On("A")}
}

func (_c *InterfaceAMock_A_Call) Run(run func()) *InterfaceAMock_A_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InterfaceAMock_A_Call) Return() *InterfaceAMock_A_Call {
	_c.Call.Return()
	return _c
}

func (_c *InterfaceAMock_A_Call) RunAndReturn(run func()) *InterfaceAMock_A_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields: _a0
func (_m *InterfaceAMock) Close(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InterfaceAMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type InterfaceAMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *InterfaceAMock_Expecter) Close(_a0 interface{}) *InterfaceAMock_Close_Call {
	return &InterfaceAMock_Close_Call{Call: _e.mock.On("Close", _a0)}
}

func (_c *InterfaceAMock_Close_Call) Run(run func(_a0 context.Context)) *InterfaceAMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *InterfaceAMock_Close_Call) Return(_a0 error) *InterfaceAMock_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InterfaceAMock_Close_Call) RunAndReturn(run func(context.Context) error) *InterfaceAMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewInterfaceAMock creates a new instance of InterfaceAMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterfaceAMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *InterfaceAMock {
	mock := &InterfaceAMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
