// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TestingTMock is an autogenerated mock type for the TestingT type
type TestingTMock struct {
	mock.Mock
}

type TestingTMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TestingTMock) EXPECT() *TestingTMock_Expecter {
	return &TestingTMock_Expecter{mock: &_m.Mock}
}

// Errorf provides a mock function with given fields: format, args
func (_m *TestingTMock) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// TestingTMock_Errorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorf'
type TestingTMock_Errorf_Call struct {
	*mock.Call
}

// Errorf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *TestingTMock_Expecter) Errorf(format interface{}, args ...interface{}) *TestingTMock_Errorf_Call {
	return &TestingTMock_Errorf_Call{Call: _e.mock.On("Errorf",
		append([]interface{}{format}, args...)...)}
}

func (_c *TestingTMock_Errorf_Call) Run(run func(format string, args ...interface{})) *TestingTMock_Errorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *TestingTMock_Errorf_Call) Return() *TestingTMock_Errorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *TestingTMock_Errorf_Call) RunAndReturn(run func(string, ...interface{})) *TestingTMock_Errorf_Call {
	_c.Run(run)
	return _c
}

// Helper provides a mock function with no fields
func (_m *TestingTMock) Helper() {
	_m.Called()
}

// TestingTMock_Helper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Helper'
type TestingTMock_Helper_Call struct {
	*mock.Call
}

// Helper is a helper method to define mock.On call
func (_e *TestingTMock_Expecter) Helper() *TestingTMock_Helper_Call {
	return &TestingTMock_Helper_Call{Call: _e.mock.On("Helper")}
}

func (_c *TestingTMock_Helper_Call) Run(run func()) *TestingTMock_Helper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TestingTMock_Helper_Call) Return() *TestingTMock_Helper_Call {
	_c.Call.Return()
	return _c
}

func (_c *TestingTMock_Helper_Call) RunAndReturn(run func()) *TestingTMock_Helper_Call {
	_c.Run(run)
	return _c
}

// NewTestingTMock creates a new instance of TestingTMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTestingTMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TestingTMock {
	mock := &TestingTMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
