---
linters:
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional linters
    - gofmt
    - gosec
    - revive
    - asasalint
    - copyloopvar
    - gci
    - gocritic
    - godot
    - gofmt
    - whitespace
    - dupword
    - testifylint
    - testpackage
    - intrange

linters-settings:
  govet:
    enable-all: true

  gosec:
    excludes:
      - G404

  revive:
    enable-all: true

  gocritic:
    enable-all: true
    disabled-checks:
      - deferInLoop # for now

  testifylint:
    enable-all: true
    disable:
      - require-error
