---
linters:
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional linters
    - gofmt
    - gosec
    - revive
    - asasalint
    - copyloopvar
    - gci
    - gocritic
    - godot
    - gofmt
    - whitespace
    - dupword
    - testifylint
    - testpackage
    - intrange
    - sloglint
    - prealloc
    - nilnil
    - errname

linters-settings:
  govet:
    enable-all: true

  gosec:
    excludes:
      - G404

  revive:
    rules:
      - name: exported
        arguments:
          - sayRepetitiveInsteadOfStutters
          - checkPublicInterface
  gocritic:
    enable-all: true
    disabled-checks:
      - deferInLoop # for now

  testifylint:
    enable-all: true
    disable:
      - require-error
  
  sloglint:
    context: "all"
    static-msg: true

  prealloc:
    for-loops: true

issues:
  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment.
    - EXC0013  # EXC0012 revive: Annoying issue about not having a comment.
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment.

  exclude-rules:
    - path: internal/...
      linters:
        - revive
      text: "^exported"
    - path: internal/...
      linters:
        - prealloc
