---
linters:
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional linters
    - gofmt
    - gosec
    - revive
    - asasalint

linters-settings:
  govet:
    enable-all: true

  gosec:
    excludes:
      - G404

  revive:
    enable-all: true
