dir: internal/mocks
outpkg: mocks
filename: "{{.InterfaceName | snakecase}}_mock.go"
mockname: "{{.InterfaceName}}Mock"
with-expecter: true
packages:
  github.com/sectrean/di-kit:
    interfaces:
      Scope:
  github.com/sectrean/di-kit/internal/testtypes:
    interfaces:
      InterfaceA:
      InterfaceB:
      InterfaceC:
      InterfaceD:
