dir: internal/mocks
outpkg: mocks
filename: "{{.InterfaceName | snakecase}}_mock.go"
mockname: "{{.InterfaceName}}Mock"
with-expecter: true
packages:
  github.com/johnrutherford/di-kit:
    interfaces:
      Closer:
      Scope:
        config:
          dir: .
          filename: "scope_mock_test.go"
          inpackage: true
          mockname: "scopeMock"
  github.com/johnrutherford/di-kit/internal/testtypes:
    interfaces:
      InterfaceA:
      InterfaceB:
      InterfaceC:
      InterfaceD:
