version: '3'

tasks:
  setup:
    cmds:
      - go mod download -x

  build:
    cmds:
      - go build -v ./...

  test:
    cmds:
      - go test -coverprofile=coverage.txt -timeout 10s -race -v ./...

  bench:
    cmds:
      - go test -bench=. -benchmem ./...

  mocks:
    cmds:
      - mockery

  lint:
    cmds:
      - golangci-lint run -v
