version: '3'

tasks:
  build:
    cmds:
      - go build -v ./...

  test:
    cmds:
      - go test -race -v ./...

  bench:
    cmds:
      - go test -bench=. -benchmem ./...

  mocks:
    cmds:
      - mockery